# Generated by Django 5.0.6 on 2024-07-28 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stickies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creatorId', models.CharField(max_length=255)),
                ('sticky', models.CharField(max_length=500)),
            ],
        ),
    ]
