# Generated by Django 5.0.6 on 2024-07-28 17:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0002_stickies'),
    ]

    operations = [
        migrations.AddField(
            model_name='stickies',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
